name: Composer validation

on:
  workflow_dispatch:
  push:
    paths:
      - composer.json
      - src/**
  pull_request:
    paths:
      - composer.json
      - src/**

jobs:
  composer:
    name: Composer validation
    runs-on: ubuntu-latest
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install Composer Require Checker
        run: composer install --working-dir=tools/composer-require-checker

      - name: Install project dependencies
        run: composer install

      - name: Run Composer Require Checker
        run: tools/composer-require-checker/vendor/bin/composer-require-checker check --config-file=.composer-require-checker.json
