name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }}${{ matrix.composer-prefer-lowest && ', with lowest dependencies' || '' }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '7.4', '8.0' ]
        composer-prefer-lowest: [ false, true ]
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install project dependencies
        run: composer update ${{ matrix.composer-prefer-lowest && '--prefer-lowest' || '' }}

      - name: Run PHPUnit
        run: vendor/bin/phpunit
